export { default as Home } from "./Home";
export { default as Blog } from "./Blog";
export { default as Error } from "./Error";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as MyReview } from "./MyReview";
export { default as AddServices } from "./AddServices";
export { default as Services } from "./Services";
export { default as ServiceDetail } from "./ServiceDetail";
